# Generated by Django 4.2.7 on 2025-12-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo de consulta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contactado')),
                ('contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contacto')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='pets.pet', verbose_name='Mascota')),
                ('preferred_veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'VETERINARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario preferido')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('veterinarian', models.ForeignKey(limit_choices_to={'role': 'VETERINARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Bloque de Tiempo',
                'verbose_name_plural': 'Bloques de Tiempo',
                'ordering': ['date', 'start_time'],
                'unique_together': {('veterinarian', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Fecha de la cita')),
                ('appointment_time', models.TimeField(verbose_name='Hora de la cita')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo de consulta')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('confirmed_24h', models.BooleanField(default=False, verbose_name='Confirmada 24h antes')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('receptionist_notes', models.TextField(blank=True, null=True, verbose_name='Notas de recepción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet', verbose_name='Mascota')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_appointments', to='appointments.appointment', verbose_name='Reprogramada desde')),
                ('time_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='appointments.timeslot', verbose_name='Bloque de tiempo')),
                ('veterinarian', models.ForeignKey(limit_choices_to={'role': 'VETERINARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinarian_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
