# Generated by Django 4.2.7 on 2025-12-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('ACCESORIO', 'Accesorio'), ('HIGIENE', 'Higiene'), ('JUGUETE', 'Juguete'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock mínimo')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de barras')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('receptionist', models.ForeignKey(limit_choices_to={'role': 'RECEPCIONISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
            },
        ),
        migrations.CreateModel(
            name='ProductReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contacto')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reserva de Producto',
                'verbose_name_plural': 'Reservas de Productos',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
