# Generated by Django 4.2.7 on 2025-12-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('species', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], max_length=20, verbose_name='Especie')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza')),
                ('gender', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Microchip')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visita')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo de consulta')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment', models.TextField(verbose_name='Tratamiento')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Prescripción')),
                ('weight_at_visit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso en la visita (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('next_visit', models.DateField(blank=True, null=True, verbose_name='Próxima visita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet', verbose_name='Mascota')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'ordering': ['-visit_date'],
            },
        ),
    ]
