# Generated by Django 4.2.7 on 2025-12-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('species', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], max_length=20, verbose_name='Especie')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza')),
                ('gender', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('owner_email', models.EmailField(max_length=254, unique=True, verbose_name='Email del dueño')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Nombre del dueño')),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Reclamada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pre-registro')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pets', to=settings.AUTH_USER_MODEL, verbose_name='Reclamada por')),
            ],
            options={
                'verbose_name': 'Mascota Pre-registrada',
                'verbose_name_plural': 'Mascotas Pre-registradas',
                'ordering': ['-created_at'],
            },
        ),
    ]
